# nginx/conf.d/00-default.conf
server {
    listen 80 default_server;
    listen 443 ssl default_server;
    server_name _;

    # 자체 서명 인증서 (IP 접속 시 TLS 핸드셰이크용, 아무거나)
    ssl_certificate     /etc/letsencrypt/live/api.irummate.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.irummate.com/privkey.pem;

    return 444;   # 연결을 그냥 끊음 (응답 없이)
}